# proto-file: tools/metadata/proto/metadata.proto
# proto-message: Metadata
# https://fuchsia.dev/fuchsia-src/development/source_code/metadata

last_reviewed_date: {
  year: 2025
  month: 1
  day: 13
}

trackers: {
  issue_tracker: {
    component_id: 1459703
  }
}
