#!/bin/bash
# Copyright 2025 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

### Test expected behavior of 'fx unset-device'

BT_FILE_DEPS=(
    "scripts/fx"
    "tools/devshell/lib/vars.sh"
    "tools/devshell/unset-device"
    "tools/devshell/lib/fx-cmd-locator.sh"
    "tools/devshell/lib/fx-optional-features.sh"
    "tools/devshell/lib/platform.sh"
    "tools/devshell/lib/generate-ssh-config.sh"
)

declare fx

BT_MKDIR_DEPS=(
    "out/default"
)

BT_SET_UP() {
    source "${BT_TEMP_DIR}/tools/devshell/tests/lib/fuchsia-mock.sh"
    fx="$(btf::setup_fx)"
    FUCHSIA_DIR="${BT_TEMP_DIR}"
}

# Check that the device file is removed when unsetting the device
TEST_fx-unset-device-removes-file() {
    local device_file="${FUCHSIA_DIR}/out/default.device"
    echo "foo" >"${device_file}"

    BT_EXPECT ${fx} unset-device 2>/dev/null
    BT_EXPECT_FILE_DOES_NOT_EXIST ${device_file}
}

# Check that the device file is removed when unsetting the device with a non-default build-dir
TEST_fx-unset-device-writes-file-non-standard-build-dir() {
    local rel_build_dir="out/foo"
    local build_dir="${FUCHSIA_DIR}/${rel_build_dir}"
    local device_file="${build_dir}.device"
    echo "${rel_build_dir}" >"${FUCHSIA_DIR}/.fx-build-dir"
    mkdir -p "${build_dir}"
    cat >"${build_dir}/fx.config" <<EOF
FUCHSIA_BUILD_DIR="${FUCHSIA_DIR}/out/foo"
EOF

    echo "foo" >"${device_file}"

    BT_EXPECT ${fx} unset-device 2>/dev/null
    BT_EXPECT_FILE_DOES_NOT_EXIST ${device_file}
}

# Check that the command fails if used with -t
TEST_fx-unset-device-fails-with-device-flag() {
    BT_EXPECT_FAIL ${fx} -t foo unset-device foo 2>/dev/null
}

# test that we warn the user if the set command will be a noop
TEST_fx-unset-device-warns-if-nodename-env-var-set-already() {
    local out="${BT_TEMP_DIR}/_fx_set_device_output"
    export FUCHSIA_NODENAME="bar"

    # Do not fail, just warn
    BT_EXPECT ${fx} unset-device >"$out" 2>&1

    # Check that the output contains the text
    BT_EXPECT_FILE_CONTAINS_SUBSTRING "${out}" "WARNING: FUCHSIA_NODENAME is already set to ${FUCHSIA_NODENAME}"
    BT_EXPECT_FILE_CONTAINS_SUBSTRING "${out}" "WARNING: Calling fx unset-device will remove the <build-dir>.device file but it will not"
    BT_EXPECT_FILE_CONTAINS_SUBSTRING "${out}" "unset FUCHSIA_NODENAME meaning that the default target will still be set"
}

BT_RUN_TESTS "$@"
