# proto-file: tools/metadata/proto/metadata.proto
# proto-message: Metadata
# https://fuchsia.dev/fuchsia-src/development/source_code/metadata

last_reviewed_date: {
  year: 2025
  month: 2
  day: 27
}

trackers: {
  issue_tracker: {
    # Fuchsia > Fuchsia Testing Architecture > Platform
    component_id: 1436363
  }
}

presubmits: {
  auto_reviewers: "cphoenix@google.com"
}
