#!/bin/bash

# Wait for the piped-in "led launch" to finish. Afterwards, produce an exit
# status that corresponds to that of the run.

set -e
set -o pipefail

bbid=$(jq -r .buildbucket.build_id)
status=$(bb collect -fields status -json $bbid | jq -r .status)
[[ "$status" = "SUCCESS" ]]
