#!/bin/bash

# Re-run the given builder at HEAD of the current git repo.
# Wait for it to finish and produce an exit status that corresponds to that of the run.

# This can be used as a git bisect script:
# $ git bisect run led-try-head <builder>

set -o pipefail

led get-builder "$@" | led edit -pa revision=$(git rev-parse HEAD) | led launch | "$(dirname "$0")/led-wait-for-status"

