#!/bin/bash
# Copyright 2025 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

#### CATEGORY=Build
### set which product bundle to build in a multi-product environment

## usage: fx set-main-pb <product-bundle-name>

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
source "$SCRIPT_DIR/lib/vars.sh" || exit $?

fx-config-read

set -e

if [[ $# -ne 1 ]]; then
  fx-command-help
  exit 1
fi

JQ_FILTER="first(.[] | select(((.label | split(\"(\"))[0] == \"$1\") or .name == \"$1\") | .label)"
LABEL=$(fx-command-run jq -r "$JQ_FILTER" "$FUCHSIA_BUILD_DIR/product_bundles.json")
LABEL=${LABEL%\(*}

if [[ -z $LABEL ]]; then
  echo "product_bundles.json does not contain product: $1"
  echo ""

  AVAILABLE=$(fx-command-run jq -r ".[].name" "$FUCHSIA_BUILD_DIR/product_bundles.json")
  if [[ -z $AVAILABLE ]]; then
    echo "product_bundles.json does not contain ANY products"
    echo "Try adding some to 'product_bundle_labels'"
  else
    echo "Found:"
    while IFS= read -r line; do
        echo "  $line"
    done <<< "$AVAILABLE"
  fi
  exit 1
fi

GN_ARGS_ENTRY="main_pb_label = \"$LABEL\""

OUT="$FUCHSIA_BUILD_DIR/args.gn"
TMP="$OUT.tmp"
rm -f $TMP

PRETTY_OUT=${OUT#$FUCHSIA_DIR/}

# Loop over every line in args.gn.
found=false
while IFS= read -r line; do
  if [[ $line == $GN_ARGS_ENTRY ]]; then
    # Exit early, because we already have this main PB set.
    echo "main_pb_label already set to $LABEL."
    echo "args.gn not changed."
    rm -f $TMP
    exit 0
  elif [[ $line =~ "main_pb_label" ]]; then
    # Replace the current main PB with the new one.
    echo "Adding to $PRETTY_OUT:"
    echo "  $GN_ARGS_ENTRY"
    found=true
    echo "$GN_ARGS_ENTRY" >> $TMP
  else
    # Not a relevant line, so pass it through.
    echo "${line}" >> $TMP
  fi
done < "$OUT"

# If we didn't find an existing main PB, then we add it to the end.
if [[ "$found" = false ]]; then
  echo "$GN_ARGS_ENTRY" >> $TMP
fi

# Replace the real args.gn with the temporary file.
mv $TMP $OUT

echo ""
echo "Running 'fx gen'"
echo "..."
fx-gen
