#!/bin/bash
# Copyright 2025 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

#### CATEGORY=Build
### set which product bundle to build in a multi-product environment

## usage: fx set-main-pb <product-bundle-name>

readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
source "$SCRIPT_DIR/lib/vars.sh" || exit $?

fx-config-read

set -e

if [[ $# -ne 1 ]]; then
  fx-command-help
  exit 1
fi

JQ_FILTER="first(.[] | select(((.label | split(\"(\"))[0] == \"$1\") or .name == \"$1\") | .label)"
LABEL=$(fx-command-run jq -r "$JQ_FILTER" "$FUCHSIA_BUILD_DIR/product_bundles.json")
LABEL=${LABEL%\(*}

if [[ -z $LABEL ]]; then
  echo "product_bundles.json does not contain product: $1"
  echo ""

  AVAILABLE=$(fx-command-run jq -r ".[].name" "$FUCHSIA_BUILD_DIR/product_bundles.json")
  if [[ -z $AVAILABLE ]]; then
    echo "product_bundles.json does not contain ANY products"
    echo "Try adding some to 'product_bundle_labels'"
  else
    echo "Found:"
    while IFS= read -r line; do
        echo "  $line"
    done <<< "$AVAILABLE"
  fi
  exit 1
fi

GN_ARGS_ENTRY="main_pb_label = \"$LABEL\""

OUT="$FUCHSIA_BUILD_DIR/args.gn"
TMP="$OUT.tmp"
rm -f $TMP

PRETTY_OUT=${OUT#$FUCHSIA_DIR/}
echo "Adding to $PRETTY_OUT:"
echo "  $GN_ARGS_ENTRY"

found=false
while IFS= read -r line; do
  if [[ $line =~ "main_pb_label" ]]; then
    found=true
    echo "$GN_ARGS_ENTRY" >> $TMP
  else
    echo $line >> $TMP
  fi
done < "$OUT"
if [[ "$found" = false ]]; then
  echo "$GN_ARGS_ENTRY" >> $TMP
fi
mv $TMP $OUT
rm -f $TMP

echo ""
echo "Running 'fx gen'"
echo "..."
fx-gen
