#!/bin/bash
# Copyright 2024 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

#### CATEGORY=Build
### build the current default product bundle

## usage: fx build-product

echo "This command is deprecated in favor of 'fx set-main-pb' and 'fx build'"
echo "This will be removed in https://fxbug.dev/397689721"

# TODO(https://fxbug.dev/397689721): Remove after a month of soaking.
