#!/usr/bin/env bash
# Copyright 2024 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

#### CATEGORY=Other
### Flash Fuchsia onto a Kola board that has an unmodified bootloader. Install the user's public SSH
### key onto the device via serial console (using default path /dev/ttyUSB0 if unspecified).

## usage: fx flash-kola [serial_console_path]
##  e.g.: fx flash-kola /tmp/pontis/serial-10c4-ea60

# Bash strict mode.
set -eo pipefail

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/../lib/vars.sh || exit $?
fx-config-read

# Use the in-tree fastboot.
readonly FASTBOOT="${FUCHSIA_DIR}/prebuilt/third_party/fastboot/fastboot"


# TODO(b/373727276): Change to use `ffx target flash` instead.
FLASH_SOURCE="$(fx-command-run get-flash-source)"
PRODUCT_BUNDLE="$(fx get-build-dir)/${FLASH_SOURCE#product-bundle:}"
ARTIFACTS="${PRODUCT_BUNDLE}/product_bundle.json"
DTBO_PATH="${PRODUCT_BUNDLE}/$(fx-command-run jq --raw-output '.system_a[] | select(.name=="dtbo-a") | .path' "${ARTIFACTS}")"
FVM_PATH="${PRODUCT_BUNDLE}/$(fx-command-run jq --raw-output '.system_a[] | select(.name=="storage-full") | .path' "${ARTIFACTS}")"
ZBI_PATH="${PRODUCT_BUNDLE}/$(fx-command-run jq --raw-output '.system_a[] | select(.name=="zircon-a") | .path' "${ARTIFACTS}")"

readonly FVM_PATH ZBI_PATH DTBO_PATH

DEVICE_COUNT=$(${FASTBOOT} devices | awk NF | wc -l)
readonly DEVICE_COUNT
if [[ ${DEVICE_COUNT} -ne 1 ]]; then
  fx-error "Detected ${DEVICE_COUNT} devices in fastboot mode. Make sure there is only one device."
  exit 1
fi

# Get serial console path to device.
readonly SERIAL_PATH=${1:-'/dev/ttyUSB0'}

if [[ ! -e "${SERIAL_PATH}" ]]; then
  echo "Serial device ${SERIAL_PATH} not detected, skipping SSH key deployment."
  read -r -p "Press enter to continue..."
else
  if [[ $# -eq 0 ]]; then
    echo "The user's public SSH key will be installed onto the device using the serial console at" \
        "${SERIAL_PATH}."
    echo "Alternatively, you can supply the serial console path to be used, e.g.:"
    echo "  fx flash-kola /tmp/pontis/serial-10c4-ea60"
    read -r -p "Press enter to continue..."
  fi

  if [[ "${SERIAL_PATH}" =~ (pontis)|(/dev/pts/) ]]; then
    echo "If the serial console is over pontis, it must be an unused connection."
    echo "Else, disconnect and reconnect it at http://pontis/ on your laptop."
    read -r -p "Press enter to continue..."
  fi

  stty -F "${SERIAL_PATH}" 115200 raw -echo
fi


${FASTBOOT} flash boot_a "$ZBI_PATH"
${FASTBOOT} flash boot_b "$ZBI_PATH"
${FASTBOOT} flash dtbo_a "$DTBO_PATH"
${FASTBOOT} flash dtbo_b "$DTBO_PATH"
${FASTBOOT} flash super "$FVM_PATH"

${FASTBOOT} reboot


if [[ -e "${SERIAL_PATH}" ]]; then
  # Wait until device has completed bootup.
  sleep 60

  # Install user's public SSH key (the first one in $AUTHKEYS_PATH).
  AUTHKEYS_PATH="$(get-ssh-authkeys)"
  readonly AUTHKEYS_PATH
  echo "echo \"$(head -n 1 "${AUTHKEYS_PATH}")\" > /data/ssh/authorized_keys" > "${SERIAL_PATH}"
fi

echo "Done flashing Kola device."
