#!/bin/bash
# Copyright 2024 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

#### CATEGORY=Build
### print the current main product bundle's label

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/../lib/vars.sh || exit $?
fx-standard-switches "$@"
fx-config-read

if [[ ! -d "${FUCHSIA_BUILD_DIR}" ]]; then
  fx-error "Build directory ${FUCHSIA_BUILD_DIR} does not exist, run \"fx set\" first."
  exit 1
fi

set -e

# Make sure the build directory config is up to date before querying ffx config.
# Send stdout to stderr to avoid polluting script output.
>&2 fx-command-run build //src/developer/ffx:ffx_build_dir_config_file

product_path=$(fx-command-run ffx config get product.path | tr -d '"')
product_path=$(realpath -s "--relative-to=$FUCHSIA_BUILD_DIR" "$product_path")

# Find the label of the product bundle whose path matches the one configured for ffx.
JQ_FILTER="first(.[] | select(.path == \"$product_path\") | .label)"
BUILD_LABEL=$(fx-command-run jq -r "$JQ_FILTER" "$FUCHSIA_BUILD_DIR/product_bundles.json")

if [[ -z $BUILD_LABEL ]]; then
    echo "No matching product found!" >&2
    exit 1
fi

echo $BUILD_LABEL
