#!/bin/bash
# Copyright 2024 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

#### CATEGORY=Build
### set the main product bundle for the current build directory

## usage: fx set-product //path/to/product:bundle
##
## fx set-product is used to specify the default product to target for
## the current Fuchsia build directory, i.e. $FUCHSIA_BUILD_DIR.
##
## Intended for use with multi-product builds.

# -e exit immediately on commmand failure
# -o pipefail the return value is the value of rightmost command in a pipeline.
set -e -o pipefail

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"/../lib/vars.sh || exit $?
fx-standard-switches "$@"
fx-config-read

if [[ ! -d "${FUCHSIA_BUILD_DIR}" ]]; then
  fx-error "Build directory ${FUCHSIA_BUILD_DIR} does not exist, run \"fx set\" first."
  exit 1
fi

set -e

product="$1"
new_product_path=$(fx-command-run get-product-path "${product}")

ffx_config="${FUCHSIA_BUILD_DIR}/ffx-config.json"
cp "${ffx_config}" "${ffx_config}.backup"

fx-command-run jq ".product.path = \"\$BUILD_DIR/${new_product_path}\"" "${ffx_config}.backup" > "${ffx_config}"

echo "Default product for '${FUCHSIA_BUILD_DIR}' is now ${product}"
rm "${ffx_config}.backup"
