#!/bin/bash
# Copyright 2019 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

#### CATEGORY=Run, inspect and debug
### generate a report of error conditions, with Google-specific rules.

## usage: fx vendor google triage
## Processes "fx snapshot" output looking for problems specified in a config
## file. If no snapshot output is specified (no '--data') it runs a new
## "fx snapshot" and uses its "inspect.json" file.
##
## This command is a direct call through to `ffx triage`, and using that
## directly is likely a bit more performant.
##
## See "fx triage --help" for full usage information.

fx ffx --config "triage.enabled=true" triage "$@"
