#!/bin/bash
# Copyright 2025 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

#### CATEGORY=Build
### Update the Bazel vendor directory to include all necessary Bazel deps.

## usage: fx update-bazel-vendor-dir

# shellcheck source=/dev/null
source "${FUCHSIA_DIR}/tools/devshell/lib/vars.sh" || exit $?
fx-config-read

if [[ ! -d "${FUCHSIA_BUILD_DIR}" ]]; then
  fx-error "No Fuchsia build directory, please run 'fx set' or 'fx use'."
fi

# shellcheck source=/dev/null
source "${FUCHSIA_DIR}/tools/devshell/lib/bazel_utils.sh" || exit $?
fx-update-bazel-workspace

"${PREBUILT_PYTHON3}" "${FUCHSIA_DIR}"/build/bazel/scripts/update_bazel_vendor_dir.py \
    --workspace="$(fx-get-bazel-workspace)" \
    --bazel="$(fx-get-bazel)" \
    --bazel-vendor-dir="${FUCHSIA_DIR}/third_party/bazel_vendor" \
    --repo='@@bazel_features+' \
    --repo='@@bazel_skylib+' \
    --repo='@@platforms' \
    --repo='@@rules_cc+' \
    --repo='@@rules_go+' \
    --repo='@@rules_java+' \
    --repo='@@rules_license+' \
    --repo='@@rules_proto+' \
    --repo='@@rules_python+' \
    --repo='@@rules_shell+' \
    --stub-repo='@@apple_support+' \
    --stub-repo='@@bazel_tools+remote_coverage_tools_extension+remote_coverage_tools'
