## require is_lto=false
## require optimize=none

[zxdb] run-component fuchsia-pkg://fuchsia.com/zxdb_e2e_inferiors#meta/async_rust_multithreaded.cm
Launched Process 1 state=Running koid=?? name=async_rust_multithreaded.cm component=async_rust_multithreaded.cm
🛑

[zxdb] abt
Task(id = 0)
└─ async_rust_multithreaded::main::func • async_rust_multithreaded.rs:??
   └─ fuchsia_async::runtime::fuchsia::timer::Timer

[zxdb] pause
[zxdb] t 2
[zxdb] abt
Task(id = 0)
└─ async_rust_multithreaded::main::func • async_rust_multithreaded.rs:??
   └─ fuchsia_async::runtime::fuchsia::timer::Timer

[zxdb] t 3
[zxdb] abt
Task(id = 0)
└─ async_rust_multithreaded::main::func • async_rust_multithreaded.rs:??
   └─ fuchsia_async::runtime::fuchsia::timer::Timer

[zxdb] kill
Process 1 killed.
