## require optimize=none

[zxdb] b pretty_types.rs:51
Created Breakpoint 1

[zxdb] run-component fuchsia-pkg://fuchsia.com/zxdb_e2e_inferiors#meta/pretty_types_rust.cm
🛑 on bp 1

# Pretty prints the vector correctly even with a shadowing type naming conflict, and erased types in
# the underlying storage for various types that use std::vec::Vec.
[zxdb] locals
BinaryHeap<pretty_types_rust::NestedType, alloc::alloc::Global>[
  [0]: NestedType{num: 10}
  [1]: NestedType{num: 8}
  [2]: NestedType{num: 4}
  [3]: NestedType{num: 2}
  [4]: NestedType{num: 6}
]
os_str = "osstr"
s = "hello"
NestedVecs{
  input: vec![
    [0]: NestedType{num: 1}
    [1]: NestedType{num: 2}
    [2]: NestedType{num: 3}
    [3]: NestedType{num: 4}
  ]
  output: vec![
    [0]: NestedType{num: 6}
    [1]: NestedType{num: 7}
    [2]: NestedType{num: 8}
    [3]: NestedType{num: 9}
  ]
}
