## require optimize=none

[zxdb] b pretty_types.rs:44
Created Breakpoint 1 @ pretty_types.rs:44

[zxdb] run-component fuchsia-pkg://fuchsia.com/zxdb_e2e_inferiors#meta/pretty_types_rust.cm
🛑 on bp 1

[zxdb] up
Frame 1 pretty_types_rust::main()

# Pretty prints the vector correctly even with a shadowing type naming conflict.
[zxdb] p v
NestedVecs{
  input: vec![
    [0]: NestedType{num: 1}
    [1]: NestedType{num: 2}
    [2]: NestedType{num: 3}
    [3]: NestedType{num: 4}
  ]
  output: vec![
    [0]: NestedType{num: 6}
    [1]: NestedType{num: 7}
    [2]: NestedType{num: 8}
    [3]: NestedType{num: 9}
  ]
}
