## require optimize=none

[zxdb] b pretty_types.cc:33
Created Breakpoint 1 @ pretty_types.cc:33

[zxdb] run-component fuchsia-pkg://fuchsia.com/zxdb_e2e_inferiors#meta/pretty_types.cm
🛑 on bp 1 main() • pretty_types.cc:33

[zxdb] locals
map = {{first = "a", second = 1}, {first = "b", second = 2}}
p = (*)?? ➔ {Parent = {a = 0}, b = 1}
set = {2, 1, 0}
span = {'b', 'c'}
sv = "abc"
up = (*)?? ➔ {Parent = {a = 0}, b = 1}
