[zxdb] run-component fuchsia-pkg://fuchsia.com/crasher#meta/rust_crasher.cm
🛑

# Don't depend on the exact number of frames that are elided, since we wildcard match them anyway,
# we just want to make sure that they are elided.
[zxdb] frame --force-remote-unwind
# Note that we cannot depend on the top of the stack matching due to these e2e tests not having
# access to the rust stdlib symbols (this is also why we need to unwind on the target instead of the
# host. The bottom of the stack does contain some symbols from std but they're embedded directly
# into the binary and so are resolvable. The same is true for the below as well.
rust_crasher::main
«Rust startup»
