# Starnix doesn't work with asan right now. LTO can cause execute_syscall to be inlined
# which breaks unwinding into user code.
## require is_asan=false
## require is_lto=false
## require is_thinlto=false
## require optimize=none
## set timeout 30

# TODO(https://fxbug.dev/42077983): attach shouldn't be necessary.
# The name "starnix_proc_exception" is truncated to "starnix_proc_exception" (no trailing 'n').
[zxdb] attach starnix_proc_exception
Waiting for process matching "starnix_proc_exception".

[zxdb] run-test --realm /core/testing/system-tests fuchsia-pkg://fuchsia.com/zxdb_e2e_inferiors#meta/starnix_proc_exception.cm
Attached Process 1 state=Running koid=?? name=data/bin/starnix_proc_exception component=starnix_kernel.cm

🛑 software_break(uint64_t) • backtrace-request.h:??

# Zxdb can unwind into restricted stack.
[zxdb] f
# When optimization is on, there might be other inlined frame so we only check
# the existence of the main function in the backtrace.
main() • starnix_proc_exception.cc

[zxdb] kill
