# Starnix doesn't work with asan right now. LTO can cause execute_syscall to be inlined
# which breaks unwinding into user code.
## require is_asan=false
## require is_lto=false
## require is_thinlto=false
## require optimize=none
## set timeout 30

# TODO(https://fxbug.dev/42077983): attach shouldn't be necessary.
[zxdb] attach starnix_proc
Waiting for process matching "starnix_proc".

[zxdb] b -t execute execute_syscall
Created Breakpoint 1 type=execute @ execute_syscall

[zxdb] run-test --realm /core/testing/system-tests fuchsia-pkg://fuchsia.com/zxdb_e2e_inferiors#meta/starnix_proc.cm
Attached Process 1 state=Running koid=?? name=data/bin/starnix_proc component=starnix_kernel.cm
🛑 on bp 1

[zxdb] bp rm
Removed Breakpoint 1 type=execute @ execute_syscall

[zxdb] c
Process 1 exited with code 0.
