// Copyright 2021 The Fuchsia Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef SRC_GRAPHICS_DISPLAY_DRIVERS_AMLOGIC_DISPLAY_VOUT_H_
#define SRC_GRAPHICS_DISPLAY_DRIVERS_AMLOGIC_DISPLAY_VOUT_H_

#include <fidl/fuchsia.images2/cpp/wire.h>
#include <fuchsia/hardware/display/controller/c/banjo.h>
#include <lib/device-protocol/display-panel.h>
#include <lib/driver/incoming/cpp/namespace.h>
#include <lib/inspect/cpp/inspect.h>
#include <lib/zx/result.h>
#include <zircon/errors.h>
#include <zircon/types.h>

#include <cstdint>
#include <memory>

#include "src/graphics/display/drivers/amlogic-display/clock.h"
#include "src/graphics/display/drivers/amlogic-display/dsi-host.h"
#include "src/graphics/display/drivers/amlogic-display/hdmi-host.h"
#include "src/graphics/display/drivers/amlogic-display/panel-config.h"
#include "src/graphics/display/lib/api-types/cpp/display-id.h"
#include "src/graphics/display/lib/api-types/cpp/display-timing.h"
#include "src/graphics/display/lib/api-types/cpp/mode-id.h"
#include "src/graphics/display/lib/api-types/cpp/mode.h"

namespace amlogic_display {

enum class VoutType : uint8_t {
  kDsi,
  kHdmi,
};

// Represents the Video Output (VOUT) module and the connected display device.
class Vout {
 public:
  // Returns a non-null pointer to the Vout instance outputting DSI signal on
  // success.
  static zx::result<std::unique_ptr<Vout>> CreateDsiVout(fdf::Namespace& incoming,
                                                         display::PanelType panel_type,
                                                         inspect::Node node);

  // Returns a non-null pointer to the Vout instance outputting HDMI signal on
  // success.
  static zx::result<std::unique_ptr<Vout>> CreateHdmiVout(fdf::Namespace& incoming,
                                                          inspect::Node node,
                                                          uint8_t visual_debug_level);

  // Sets only the display feature bits and panel settings for testing.
  // Returns a non-null pointer to the Vout instance on success.
  static zx::result<std::unique_ptr<Vout>> CreateDsiVoutForTesting(display::PanelType panel_type);

  // Creates a Vout instance that outputs MIPI-DSI signal.
  //
  // `panel_config` must be non-null and must outlive the `Vout` instance.
  Vout(std::unique_ptr<DsiHost> dsi_host, std::unique_ptr<Clock> dsi_clock,
       const PanelConfig* panel_config, inspect::Node node);

  // Creates a Vout instance that outputs HDMI signal.
  Vout(std::unique_ptr<HdmiHost> hdmi_host, inspect::Node node, uint8_t visual_debug_level);

  Vout(Vout&&) = delete;
  Vout(const Vout&) = delete;
  Vout& operator=(Vout&&) = delete;
  Vout& operator=(const Vout&) = delete;

  // `pixel_formats` must outlive the returned added_display_args_t.
  raw_display_info_t CreateRawDisplayInfo(
      display::DisplayId display_id,
      cpp20::span<const fuchsia_images2_pixel_format_enum_value_t> pixel_formats);

  VoutType type() { return type_; }
  bool supports_hpd() const { return supports_hpd_; }

  zx::result<> UpdateStateOnDisplayConnected();
  void DisplayDisconnected();

  display::Mode CurrentDisplayMode() const;

  // Vout must be of `kHdmi` type.
  bool IsDisplayTimingSupported(const display::DisplayTiming& timing);

  // Vout must be of `kHdmi` type.
  zx::result<> ApplyConfiguration(const display::DisplayTiming& timing);

  // Attempt to turn off all connected displays, and disable clocks. This will
  // also stop vsync interrupts. This is aligned with the interface for
  // fuchsia.hardware.display, where a disabled display does not produce OnVsync
  // events.
  //
  // This method is not guaranteed to power off all devices. Returns ZX_OK if
  // successful, ZX_ERR_UNSUPPORTED if the panel cannot be powered off. May
  // return other errors.
  zx::result<> PowerOff();

  // Turn on all connected displays and reprogram clocks. This will resume vsync
  // interrupts as well.
  //
  // This method is not guaranteed to power on all devices. Returns ZX_OK if
  // successful, ZX_ERR_UNSUPPORTED if the panel cannot be powered on. May
  // return other errors.
  zx::result<> PowerOn();

  // Makes the frames generated by the Video Input Unit (VIU) visible if
  // `frame_visible` is true. Otherwise, hides the frame generated by the VIU.
  //
  // Returns ZX_ERR_NOT_SUPPORTED if the Video Output Module doesn't support
  // hiding video input unit frames.
  zx::result<> SetFrameVisibility(bool frame_visible);

  void Dump();

 private:
  VoutType type_;

  // Features
  bool supports_hpd_ = false;

  inspect::Node node_;

  struct dsi_t {
    std::unique_ptr<DsiHost> dsi_host;
    std::unique_ptr<Clock> clock;

    // TODO(https://fxbug.dev/318800903): Use const reference when `dsi_` moves
    // to its own implementation class.
    PanelConfig panel_config;

    // Matches the timing in `panel_config`.
    display_mode_t banjo_mode;
  } dsi_;

  struct hdmi_t {
    std::unique_ptr<HdmiHost> hdmi_host;

    fbl::Vector<uint8_t> current_display_edid;

    display::DisplayTiming current_display_timing_;
  } hdmi_;

  uint8_t visual_debug_level_;
};

}  // namespace amlogic_display

#endif  // SRC_GRAPHICS_DISPLAY_DRIVERS_AMLOGIC_DISPLAY_VOUT_H_
