#!/usr/bin/env bash

# Copyright 2025 Mist Tecnologia Ltda. All rights reserved.
# Copyright 2016 The Fuchsia Authors
#
# Use of this source code is governed by a MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT

set -e -u

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

PROJECT_DIR="$DIR/../../out/default"
# osx prefix for grub legacy (x86_64-elf is for EFI)
GRUB_PREFIX=i686-elf-

if ! which xorriso ${GRUB_PREFIX}grub-mkrescue &> /dev/null; then
  echo "ERROR: You must install xorriso and ${GRUB_PREFIX}grub-mkrescue"
  exit
fi

mkdir -p "$PROJECT_DIR/iso/boot/grub"
cp "$PROJECT_DIR/kernel.phys32/multiboot-shim.bin" "$PROJECT_DIR/iso/boot/"
cp "$PROJECT_DIR/kernel_x64/kernel.zbi" "$PROJECT_DIR/iso/boot/"
cat > "$PROJECT_DIR/iso/boot/grub/grub.cfg" << \EOF
set timeout=0
menuentry "mist-os" {
  multiboot /boot/multiboot-shim.bin kernel.serial=legacy kernel.bypass-debuglog=true kernel.halt-on-panic=true kernel.shell=true
  module /boot/kernel.zbi
}
EOF
${GRUB_PREFIX}grub-mkrescue -o "$PROJECT_DIR/mistos.iso" "$PROJECT_DIR/iso"

# Verify ISO contents
#echo "Verifying ISO contents..."
#xorriso -indev "$PROJECT_DIR/mistos.iso" -toc
