// Copyright 2025 The Fuchsia Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef LIB_DRIVER_DEVICETREE_VISITORS_DRIVERS_INTERCONNECT_INTERCONNECT_VISITOR_TEST_DTS_INTERCONNECT_H_
#define LIB_DRIVER_DEVICETREE_VISITORS_DRIVERS_INTERCONNECT_INTERCONNECT_VISITOR_TEST_DTS_INTERCONNECT_H_

#define ICC_ID1 12
#define ICC_ID2 25
#define ICC_ID3 32
#define ICC_ID4 43
#define ICC_ID5 51
#define ICC_ID6 5

#define PATH1_NAME "A_NOC"
#define PATH2_NAME "B_NOC"
#define PATH3_NAME "C_NOC"

#endif  // LIB_DRIVER_DEVICETREE_VISITORS_DRIVERS_INTERCONNECT_INTERCONNECT_VISITOR_TEST_DTS_INTERCONNECT_H_
