// Copyright 2025 The Fuchsia Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef SRC_DIAGNOSTICS_LIB_CPP_LOG_DECODER_LOG_DECODER_H_
#define SRC_DIAGNOSTICS_LIB_CPP_LOG_DECODER_LOG_DECODER_H_

// Warning:
// This file was autogenerated by cbindgen.
// Do not modify this file manually.

#include <zircon/types.h>

#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <new>
#include <ostream>

extern "C" {

/// # Safety
///
/// Same as for `std::slice::from_raw_parts`. Summarizing in terms of this API:
///
/// - `msg` must be valid for reads for `size`, and it must be properly aligned.
/// - `msg` must point to `size` consecutive u8 values.
/// - The `size` of the slice must be no larger than `isize::MAX`, and adding
///   that size to data must not “wrap around” the address space. See the safety
///   documentation of pointer::offset.
extern "C" char *fuchsia_decode_log_message_to_json(const uint8_t *msg, uintptr_t size);

/// # Safety
///
/// This should only be called with a pointer obtained through
/// `fuchsia_decode_log_message_to_json`.
extern "C" void fuchsia_free_decoded_log_message(char *msg);

}  // extern "C"

#endif  // SRC_DIAGNOSTICS_LIB_CPP_LOG_DECODER_LOG_DECODER_H_
