#!/usr/bin/env -S python3 -B
#
# Copyright 2023 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import os, sys

sys.path.append(
    os.path.join(
        os.path.dirname(os.path.abspath(__file__)),
        "..",
        "..",
        "..",
        "..",
        "build",
        "rust",
    )
)
from bindgen import Bindgen

bindgen = Bindgen()

bindgen.raw_lines = """
//! WARNING - This file was auto generated by //src/starnix/lib/syncio/generate.py.
//! Do not modify this file. To re-generate, run the following command from the root of
//! your Fuchsia checkout:
//!
//!    ./src/starnix/lib/syncio/generate.py

use zerocopy::{AsBytes, FromBytes, NoCell, FromZeros};
"""

bindgen.include_dirs = [
    "sdk/lib/zxio/include",
    "zircon/third_party/ulib/musl/include",
    "zircon/system/public",
]

bindgen.enable_stdlib_include_dirs = False

bindgen.function_allowlist = ["zxio_.*"]
bindgen.var_allowlist = [
    "ZXIO_SHUTDOWN.*",
    "ZXIO_NODE_PROTOCOL.*",
    "ZXIO_SEEK_ORIGIN.*",
    "ZXIO_ALLOCATE.*",
    "ZXIO_CREATION_MODE.*",
    "E[A-Z]*",
    "AF_.*",
    "SO.*",
    "IP.*",
    "MSG_.*",
    "__bindgen_missing_.*",
]
bindgen.type_allowlist = [
    "cmsghdr.*",
    "in6_.*",
    "sockaddr.*",
    "timespec",
    "timeval",
]

# NOTE: Types are matched against the following identifiers as regexes in the order they appear.
bindgen.set_auto_derive_traits(
    [
        (r"cmsghdr", ["AsBytes, FromBytes", "FromZeros", "NoCell"]),
        (
            r"in_addr",
            ["PartialEq", "Eq", "AsBytes", "FromBytes", "FromZeros", "NoCell"],
        ),
        (r"in6_addr", ["AsBytes, FromBytes", "FromZeros", "NoCell"]),
        (r"in6_pktinfo", ["AsBytes, FromBytes", "FromZeros", "NoCell"]),
        # "sockaddr_in6" includes a union type preventing auto deriving Eq/PartialEq, so it
        # must appear before "sockaddr_in" in this list.
        (r"sockaddr_in6", []),
        (
            r"sockaddr_in",
            ["PartialEq", "Eq", "AsBytes", "FromBytes", "FromZeros", "NoCell"],
        ),
        (r"timespec", ["AsBytes, FromBytes", "FromZeros", "NoCell"]),
        (r"timeval", ["AsBytes, FromBytes", "FromZeros", "NoCell"]),
    ]
)

bindgen.set_replacements(
    [
        # Remove __bindgen_missing from the start of constants defined in missing_includes.h
        (r"const __bindgen_missing_([a-zA-Z_0-9]+)", "const \\1"),
    ]
)

bindgen.run(
    "src/starnix/lib/syncio/wrapper.h", "src/starnix/lib/syncio/src/zxio.rs"
)
